### ISSUE TITLE
Not able to run - invalid syntax error.

### ISSUE THREAD

**Issue by mirajgodha** [Felixoid/clickhouse-plantuml#8]
Traceback (most recent call last):
  File "/bin/clickhouse-plantuml", line 9, in <module>
    load_entry_point('clickhouse-plantuml==0.2.2', 'console_scripts', 'clickhouse-plantuml')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/clickhouse_plantuml/__init__.py", line 7, in <module>
    from .column import Column
  File "/usr/lib/python2.7/site-packages/clickhouse_plantuml/column.py", line 14
    database: str,
            ^
SyntaxError: invalid syntax

**Comment by Felixoid** [comment]
Hey. Do you use a supported python version?  
https://github.com/Felixoid/clickhouse-plantuml/blob/master/.github/workflows/tests.yml#L16

**Comment by mirajgodha** [comment]
Tried upgrading the python version: 

[root@siqperf01-mst-02 src]# python --version
Python 3.6.8

now this error:

  File "/bin/clickhouse-plantuml", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)

**Comment by Felixoid** [comment]
Sorry, can't reproduce with 3.8 and 3.9

```
┌[11:43:50] felixoid@ig-fel:/tmp
└>ѳ> git clone git@github.com:Felixoid/clickhouse-plantuml.git
Cloning into 'clickhouse-plantuml'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 193 (delta 6), reused 19 (delta 5), pack-reused 164
Receiving objects: 100% (193/193), 105.73 KiB | 207.00 KiB/s, done.
Resolving deltas: 100% (91/91), done.
┌[11:44:04] felixoid@ig-fel:/tmp
└>ѳ> cd clickhouse-plantuml
┌[11:44:09] felixoid@ig-fel:/tmp/clickhouse-plantuml [master|✔]
└>±> virtualenv venv
created virtual environment CPython3.9.0.final.0-64 in 146ms
  creator CPython3Posix(dest=/tmp/clickhouse-plantuml/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/felixoid/.local/share/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
┌[11:44:17] felixoid@ig-fel:/tmp/clickhouse-plantuml [master|✔]
└>±> source venv/bin/activate
┌[11:44:33] felixoid@ig-fel:/tmp/clickhouse-plantuml venv=(venv) [master|✔]
└>±> python setup.py install > /dev/null
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
clickhouse_driver.__pycache__.bufferedreader.cpython-39: module references __file__
clickhouse_driver.__pycache__.bufferedwriter.cpython-39: module references __file__
clickhouse_driver.__pycache__.varint.cpython-39: module references __file__
clickhouse_driver.columns.__pycache__.stringcolumn.cpython-39: module references __file__
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
  warnings.warn(msg)
┌[11:44:47] felixoid@ig-fel:/tmp/clickhouse-plantuml venv=(venv) [master|✔]
└>±> ./venv/bin/clickhouse-plantuml -o /dev/null
┌[11:45:24] felixoid@ig-fel:/tmp/clickhouse-plantuml venv=(venv) [master|✔]
└>±>
```

Any more information?

**Comment by mirajgodha** [comment]
Thanks @Felixoid let me try on new environment..

**Comment by Felixoid** [comment]
Feel free to reopen if you'll find something suspicious :-j

**Comment by mirajgodha** [comment]
Thanks @Felixoid i am able to run it.
Right now it only creates the diagram for default schema (clickhouse database), however is there a way i can create schema for other databases as well.

**Comment by Felixoid** [comment]
For sure, just take a look on `-h` argument, there's a help :-j
